### ISSUE TITLE
Website Projects and Information

### ISSUE THREAD

**Issue by clintonbuie** [amatemint/amatemint.github.io#1]
- [x] Background Picture + Description

Companies:
- [x] Base10 - https://base10.vc/
- [x] Nown - https://www.nown.us/
- [x] SoulSwipe - http://www.soulswipe.com/
- [x] MindBlownLabs - http://www.mindblownlabs.com/
- [x] Salon Mio Mio - http://www.mindblownlabs.com/
- [x] La Noria Film - http://www.lanoriafilm.com/
- [x] Phog Center - https://www.phogcenter.com/

**Comment by madkap** [comment]
updated site with these companies
